apiVersion: demo.anthos.com/v1
kind: CompositeCluster 
metadata:
  name: upbound-cluster
spec:
  compositionRef:
    # Possible values cluster-gcp-gke, cluster-aws-eks, cluster-azure-aks
    name: cluster-azure-aks
  parameters:
    # Possible values small, medium, large
    nodeSize: small
    k8sVersion: "1.24"
    fleetProject: "261832825633"
    minNodeCount: 3
    adminUsers:
    - bkauf@google.com  
  writeConnectionSecretToRef:
    namespace: default
    name: b-team
