#example composition to import existing nodegroups in AWS EKS
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: import-aws-eks-nodegroup
  labels:
    crossplane.io/xrd: compositenodepools.demo.anthos.com
    provider: aws
    cluster: eks
spec:
  compositeTypeRef:
    apiVersion: demo.anthos.com/v1
    kind:  CompositeNodepool
  patchSets:
  - name: metadata
    patches:
    - fromFieldPath: metadata.labels
  resources:
  - name: nodegoup
    base:
      apiVersion: eks.aws.gke.cloud.google.com/v1beta1
      kind: NodeGroup
      metadata:
        name: eks-ng2
        annotations:
          crossplane.io/external-name: node-group-1  # edit to match nodegroup name
      spec:
       # managementPolicy: ObserveOnly  
        providerConfigRef: 
          name: default-aws
        forProvider:
          clusterName: cluster-1
          nodeRoleArn: arn:123
          region: us-east-2
          scalingConfig: 
            - desiredSize: 2
              maxSize: 3
              minSize: 1
          subnetIds:
              - subnet-0
              - subnet-1 
              - subnet-2
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.managementPolicy
      toFieldPath: spec.managementPolicy
   - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.nodePoolName
      toFieldPath: metadata.annotations[crossplane.io/external-name]
      toFieldPath: metadata.annotations.name
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.clusterName
      toFieldPath: spec.forProvider.clusterName
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.nodeRoleArn
      toFieldPath: spec.forProvider.nodeRoleArn
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.location
      toFieldPath: spec.forProvider.region
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.desiredSize
      toFieldPath: spec.forProvider.scalingConfig[0].desiredSize
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.maxSize
      toFieldPath: spec.forProvider.scalingConfig[0].maxSize
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.minSize 
      toFieldPath: spec.forProvider.scalingConfig[0].minSize   
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.subnetIds
      toFieldPath: spec.forProvider.subnetIds
